import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Seller Margin Tools — rules and guidelines for using our free profit calculators.',
};

export default function TermsOfService() {
  return (
    <>
      <div className="bg-white border-b border-gray-100">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <h1 className="text-2xl font-bold text-gray-900">Terms of Service</h1>
        </div>
      </div>
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="prose prose-gray max-w-none space-y-6">
        <p><strong>Last updated:</strong> {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
          <p>By accessing and using Seller Margin Tools (the &quot;Website&quot;), you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use the Website.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
          <p>Seller Margin Tools provides free online calculators designed to help e-commerce sellers estimate profit margins, payment fees, and target pricing. The tools cover platforms including Amazon FBA, TikTok Shop, Shopify, and various payment processors.</p>
          <p>All calculations are performed locally in your browser. We do not store, transmit, or have access to any data you enter into the calculators.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. Disclaimer of Accuracy</h2>
          <p>The calculators on this Website provide estimates based on the fee rates and parameters you enter. These results are for informational purposes only and should not be considered financial advice.</p>
          <p>Actual fees may vary based on:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Product category and seller status</li>
            <li>Platform policy changes and fee schedule updates</li>
            <li>Regional differences in fee structures</li>
            <li>Promotional rates or volume discounts</li>
          </ul>
          <p>Always verify calculations against official platform documentation before making business decisions. We are not responsible for any financial losses resulting from reliance on our estimates.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. Intellectual Property</h2>
          <p>All content on this Website, including but not limited to text, graphics, logos, calculator formulas, and software, is the property of Seller Margin Tools and is protected by applicable intellectual property laws.</p>
          <p>You may not reproduce, distribute, modify, or create derivative works from any content on this Website without our prior written consent. You may use the calculators for personal or commercial evaluation purposes.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Acceptable Use</h2>
          <p>You agree to use the Website only for lawful purposes. You must not:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Attempt to interfere with the Website&apos;s operation or security</li>
            <li>Use automated tools to scrape or extract data from the Website</li>
            <li>Introduce malicious code or attempt to exploit vulnerabilities</li>
            <li>Use the Website in any way that could damage, disable, or impair the service</li>
            <li>Misrepresent the source or accuracy of calculations generated by the tools</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Third-Party Links and Services</h2>
          <p>The Website may contain links to third-party websites or services, including platform documentation and partner resources. These links are provided for convenience only.</p>
          <p>We do not endorse or assume responsibility for the content, privacy policies, or practices of any third-party websites. Your interactions with third-party services are governed by their respective terms and policies.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Advertising</h2>
          <p>The Website may display third-party advertisements, including through Google AdSense. Advertisers may use cookies and web beacons to serve ads based on your prior visits to the Website or other websites.</p>
          <p>You can manage your ad preferences through your Google Ad Settings or by opting out of personalized advertising through the <a href="https://www.aboutads.info/choices/" className="text-blue-600 hover:underline">Digital Advertising Alliance</a>.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Limitation of Liability</h2>
          <p>To the fullest extent permitted by applicable law, Seller Margin Tools shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Your use or inability to use the Website</li>
            <li>Any reliance on calculator results or estimates</li>
            <li>Unauthorized access to or alteration of your data</li>
            <li>Statements or conduct of any third party on the Website</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Changes to These Terms</h2>
          <p>We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting on this page. Your continued use of the Website after any changes constitutes acceptance of the updated terms.</p>
          <p>We encourage you to review this page periodically for any updates.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Governing Law</h2>
          <p>These Terms of Service shall be governed by and construed in accordance with applicable laws, without regard to conflict of law provisions.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Contact Us</h2>
          <p>If you have any questions about these Terms of Service, please contact us at:</p>
          <p>Email: <a href="mailto:taoxinglong94@gmail.com" className="text-blue-600 hover:underline">taoxinglong94@gmail.com</a></p>
        </section>
      </div>
      </div>
    </>
  );
}
